name: quotex
description: Quotex app
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

flutter_icons:
   ios: true
   android: true
   image_path: "assets/quotex.png"
   adaptive_icon_foreground: "assets/quotex.png"
   adaptive_icon_background: "assets/quotex.png"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  page_transition: ^2.0.9
  flutter_bloc: ^8.1.2
  sliding_up_panel: ^2.0.0+1
  shared_preferences: 2.0.15
  http: ^0.13.5
  onesignal_flutter: ^3.5.1
  webview_flutter: 3.0.4
  hive_generator: ^2.0.0
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.1
  galaxy_store_in_app_review: ^0.0.3
  url_launcher: ^6.1.10
  change_app_package_name: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  assets:
    - assets/
  generate: true
  fonts:
    - family: Onest
      fonts:
        - asset: fonts/OnestBold.ttf
          style: normal
          weight: 700
        - asset: fonts/OnestMedium.ttf
          weight: 500
          style: normal
        - asset: fonts/OnestRegular.ttf
          weight: 400

  uses-material-design: true
